# Base configuration for Conference Research Application
# These settings apply to all environments and can be overridden

# API Configuration
api:
  openai:
    model: "gpt-4o-mini-2024-07-18"
    max_tokens: 1000
    timeout: 30
  
  serper:
    timeout: 10
    max_results: 10
  
  groq:
    timeout: 15

# File Upload Configuration
file_upload:
  max_size_mb: 50
  allowed_extensions:
    - ".csv"
    - ".xlsx" 
    - ".xls"
  allowed_mime_types:
    - "text/csv"
    - "application/csv"
    - "text/plain"
    - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    - "application/vnd.ms-excel"
  validation_strict: true

# WebDriver Configuration
webdriver:
  timeout: 30
  headless: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# Retry Configuration
retry:
  max_attempts: 3
  initial_delay: 1.0
  backoff_factor: 2.0
  max_delay: 60.0

# Logging Configuration
logging:
  level: "INFO"
  format: "standard"
  file_enabled: false
  file_path: "logs/conference_research.log"

# Feature Flags
enable_caching: false
enable_analytics: false
