# Streamlit Secrets Configuration
# Add your API keys here. Never commit this file to version control.

# OpenAI API Configuration
openai_api_key = "your_openai_api_key_here"

# Google Serper API Configuration  
serper_api_key = "your_serper_api_key_here"

# Groq API Configuration (optional)
groq_api_key = "your_groq_api_key_here"

# Application Configuration
max_file_size_mb = 50
allowed_file_types = [".csv", ".xlsx", ".xls"]

# Security Configuration
session_secret_key = "your_session_secret_key_here"

# Example usage in Streamlit app:
# openai_key = st.secrets["openai_api_key"]
# serper_key = st.secrets["serper_api_key"]
